### ISSUE TITLE
gem registered with zzzzzcustomconfigs don't get recognised by gem detection system

### ISSUE THREAD

**Issue by RCXcrafter** [TehNut/MoreChisels#29]
I have added a gem to my modpack and I was using zzzzzcustomconfigs to add it to the oredictionary (because minetweaker adds everything when a world is opened and that's way too late for this kind of stuff). however your gem detection system doesn't pick it up when I try to make a chisel for it. I made sure that gem chisels are working with other gems.

**Comment by TehNut** [comment]
Initial guess is that I am checking for gems before yours are being registered. Still.

**Comment by RCXcrafter** [comment]
Would a log file be useful to you? If yes, here you go: https://gist.github.com/RCXcrafter/dbca0d11c33128248075
I registered clay as gemClay and added this line to the gem list: Clay:4700:#FF00CE

**Comment by TehNut** [comment]
No, what I mean is that zzzzzzzzzzzzzzzzConfigs purposely registers everything AFTER everybody else. I check and register gem chisels in the [init stage](https://github.com/TehNut/MoreChisels/blob/master/src/main/java/tehnut/morechisels/MoreChisels.java#L47). Since zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzConfigs comes later in the load order, anything done in the init stage on their end comes too late.

Looking through their Github, they are definitely registering things too late for me to interact with.
